// Generated by CoffeeScript 1.9.3
(function() {
  var displayImages, fetchImages;

  fetchImages = function(url) {
    return $.get(url).then(displayImages).fail(console.error.bind(null, 'fetchImages err'));
  };

  displayImages = function(res) {
    var html, images;
    images = res.images;
    console.log('images', images);
    html = '';
    images.forEach(function(img) {
      return html += "<a href='" + img + "' target='_blank'><img src='" + img + "'/></a>";
    });
    return $('#gallery').html(html);
  };

  fetchImages('images-list.json');

}).call(this);
