#!/usr/bin/env bash
set -e
./scripts/build-css $1

# Required to run sequentially
./scripts/build-items $1
./scripts/build-lists $1

# Compile only when build is run without option: especially "fast"
[ -z $1 ] && ./scripts/build-rss

echo 'done'
