#!/usr/bin/env node
const root = process.cwd()

const data = require('../full_data')
const _ = require('../lib/utils')

let arr = []
for (const k in data) {
  const v = data[k]
  arr.push({
    key: k,
    date: v.date,
    value: v
  })
}

arr = _.sortBy(arr, 'date')

const RSS = require('rss')

const categories = _(data)
  .map(_.property('tags'))
  .flatten()
  .compact()
  .uniq()
  .value()

const year = (new Date()).toISOString().split('-')[0]

const feed = new RSS({
  title: 'Maxime Lathuilière Web Hub',
  description: 'Where I post and link to stuffs',
  feed_url: 'https://maxlath.eu/rss.xml',
  site_url: 'https://maxlath.eu',
  image_url: 'https://maxlath.eu/assets/img/120-maxlath.jpg',
  // docs: 'https://maxlath.eu/rss/docs.html'
  managingEditor: 'Maxime Lathuilière',
  webMaster: 'Maxime Lathuilière',
  copyright: `${year} Maxime Lathuilière`,
  language: 'en',
  categories,
  // pubDate: new Date()
  ttl: 24 * 60
})

for (const el of arr) {
  const { key, value } = el
  const { title, description, cleanDesc, guid, tags, date, parent } = value
  // filter-out articles sub parts
  if (['articles', 'posts', 'projects'].includes(parent)) {
    feed.item({
      title,
      description: cleanDesc || description,
      // guid: guid
      url: `https://maxlath.eu/${key}/`,
      categories: tags,
      date
    })
  }
}

// console.log Object.keys(data)

const xml = feed.xml({ indent: true })

// console.log xml
_.writeFile('./rss.xml', xml)
