#!/usr/bin/env zsh
git push origin src &&
git checkout -B master &&
mkdir -p assets/css &&
npm run build &&
git add index.html rss.xml tags/index.html tags/**/*html projects/**/*html posts/**/*html articles/**/*html assets/css/bundle.css assets/js/index.js -f &&
git commit -m 'updated build' &&
git push origin --force master &&
git checkout src &&
mkdir -p assets/css
