#!/usr/bin/env bash
set -e

git push origin src
git checkout -B master
mkdir -p assets/css
npm run build
git add index.html rss.xml tags/index.html tags/graph.json tags/**/*html projects/**/*html posts/**/*html articles/**/*html assets/css/bundle.css -f
git commit -m 'updated build'
git push origin --force master
git checkout src
mkdir -p assets/css
