#!/usr/bin/env node
require('colors')
const cb = require('copy-paste').copy
const request = require('request')
let fs = require('fs')
let [url, ...name] = process.argv.slice(2)
name = name.join('-')
const _ = require('../lib/utils')
fs = require('fs')

if (url == null) throw new Error('missing url')
if (name == null) throw new Error('missing name')

const getImgUrl = name => {
  if (!/\./.test(name)) name = name + '.jpg'
  return `/assets/img/${name}`
}

const newUrl = getImgUrl(name)
const path = `.${newUrl}`

request.get(url)
.pipe(fs.createWriteStream(path))

cb(newUrl)
console.log('file copied, url added to clipboard'.green, newUrl)
