#!/usr/bin/env bash
# start by building
./scripts/build-html
# then watch
echo "starting to watch html"
# exclude src files that will compile in assets
onchange '(scripts|config|articles|posts|lib|tags|assets)/**' -- ./scripts/build-html
