#!/usr/bin/env sh
# start by building
./scripts/build-html
# then watch
echo "starting to watch html"
# onchange '(scripts|config|articles|posts|lib|tags)/**' -- ./scripts/build-html
onchange '.' -- ./scripts/build-html
