#!/usr/bin/env bash
# start by building
./scripts/build-items
# then watch
pattern='(projects|articles|posts)/**/(content.md|data.json)'
echo "starting to watch: $pattern -> build-items"
onchange $pattern -- ./scripts/build-items
